name: kpi_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  searchable_listview: ^2.16.0
  responsive_framework: ^1.5.1
  lucide_icons: ^0.257.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  flutter_awesome_alert_box: ^2.1.1
  shared_preferences: ^2.5.2
  fl_chart: ^0.70.2
  cupertino_sidebar: ^1.0.1
  flutter_dotenv: ^5.2.1
  rating_and_feedback_collector: ^0.0.3
  flutter_datepicker_textfield: ^1.5.1
  material_table_view: ^5.2.0
  data_table_2: ^2.6.0
  csv: ^6.0.0
  foundation: ^0.0.5
  path_provider: ^2.0.10
  permission_handler: ^11.4.0
  file_saver: ^0.2.14
  file_picker: ^10.0.0
  android_intent_plus: ^5.3.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - .env
