import 'package:flutter/material.dart';
import 'package:lucide_icons/lucide_icons.dart';

class IconDictionary {
  static const Map<String, IconData> icons = {
    'home': Icons.home,
    'search': Icons.search,
    'settings': Icons.settings,
    'person': Icons.person,
    'favorite': Icons.favorite,
    'camera': Icons.camera,
    'email': Icons.email,
    'phone': Icons.phone,
    'chat': Icons.chat,
    'alarm': Icons.alarm,
    'shopping_cart': Icons.shopping_cart,
    'lock': Icons.lock,
    'map': Icons.map,
    'menu': Icons.menu,
    'notifications': Icons.notifications,
    'star': Icons.star,
    'info': Icons.info,
    'warning': Icons.warning,
    'delete': Icons.delete,
    'edit': Icons.edit,
    'visibility': Icons.visibility,
    'package': LucideIcons.package,
    'truck': LucideIcons.truck,
    "lucide_plus_circle": LucideIcons.plusCircle,
    'visibility_off': Icons.visibility_off,
    'lucide_home': LucideIcons.home,
    'lucide_search': LucideIcons.search,
    'lucide_settings': LucideIcons.settings,
    'lucide_printer': LucideIcons.printer,
    'lucide_user': LucideIcons.user,
    'lucide_user_circle': LucideIcons.userCircle2,
    'lucide_heart': LucideIcons.heart,
    'lucide_camera': LucideIcons.camera,
    'lucide_mail': LucideIcons.mail,
    'lucide_phone': LucideIcons.phone,
    'lucide_message_circle': LucideIcons.messageCircle,
    'lucide_alarm': LucideIcons.alarmClock,
    'lucide_shopping_cart': LucideIcons.shoppingCart,
    'lucide_lock': LucideIcons.lock,
    'lucide_map': LucideIcons.map,
    'lucide_menu': LucideIcons.menu,
    'lucide_bell': LucideIcons.bell,
    'lucide_star': LucideIcons.star,
    'lucide_info': LucideIcons.info,
    'lucide_alert_triangle': LucideIcons.alertTriangle,
    'lucide_trash': LucideIcons.trash,
    'lucide_edit': LucideIcons.edit,
    'lucide_eye': LucideIcons.eye,
    'lucide_eye_off': LucideIcons.eyeOff,
  };
}
